version = '0.0.1'

dependencies {
    using platform(libs.jimmer.bom.get())
    using platform(libs.testcontainers.get())
    using platform(libs.jackson2.get())

    api 'org.babyfish.jimmer:jimmer-sql'

    implementation libs.hikari

    implementation libs.postgresql
    implementation libs.mysql
    implementation libs.mssql
    implementation libs.mariadb
    implementation libs.oracle
    implementation libs.sqlite
    implementation libs.logback.classic

    runtimeOnly 'com.fasterxml.jackson.core:jackson-core'
    runtimeOnly 'com.fasterxml.jackson.core:jackson-databind'

    implementation 'org.testcontainers:testcontainers-jdbc'

    annotationProcessor 'org.babyfish.jimmer:jimmer-apt'
}
