plugins {
    id 'io.github.honhimw.publish'
}

version = '0.4.0'
description = 'manually construct Jimmer-Module-System at runtime'

dependencies {
    using platform(libs.jimmer.bom.get())

    compileOnly 'org.babyfish.jimmer:jimmer-sql'
    compileOnly libs.jspecify
    compileOnly libs.slf4j.api
}
