plugins {
    id 'io.github.honhimw.publish'
}

version = '0.5.0'
description = 'ddl generator for jimmer'

dependencies {
    using platform(libs.jimmer.bom.get())
    using platform(libs.testcontainers.get())
    using platform(libs.jackson2.get())
    api project(':jimmer-manual')

    compileOnly 'org.babyfish.jimmer:jimmer-sql'
    compileOnly libs.jspecify
    compileOnly libs.slf4j.api

    testImplementation project(':test')
    testImplementation libs.h2
    testImplementation libs.slf4j.api
    testImplementation libs.jspecify
    testImplementation libs.hikari
    testRuntimeOnly libs.postgresql
    testRuntimeOnly libs.mysql
    testRuntimeOnly libs.mssql
    testRuntimeOnly libs.mariadb
    testRuntimeOnly libs.oracle
    testRuntimeOnly libs.sqlite
    testRuntimeOnly libs.logback.classic
    testRuntimeOnly 'com.fasterxml.jackson.core:jackson-core'
    testRuntimeOnly 'com.fasterxml.jackson.core:jackson-databind'

    testAnnotationProcessor 'org.babyfish.jimmer:jimmer-apt'

    testImplementation 'org.testcontainers:testcontainers'
    testImplementation 'org.testcontainers:testcontainers-junit-jupiter'
    testImplementation 'org.testcontainers:testcontainers-postgresql'
    testImplementation 'org.testcontainers:testcontainers-mysql'
    testImplementation 'org.testcontainers:testcontainers-mariadb'
    testImplementation 'org.testcontainers:testcontainers-mssqlserver'
    testImplementation 'org.testcontainers:testcontainers-oracle-free'
    testImplementation 'org.testcontainers:testcontainers-tidb'

}
